package sk.ics.upjs.hikeapp;

import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

public class FilterTurForm extends javax.swing.JFrame {

    private MysqlTuraDaO tury;

    public FilterTurForm() {
        initComponents();
        //naplni PohorieComboBox
        tury = new MysqlTuraDaO();
        List<String> zoznam = tury.dajZoznamPohori();
        Vector zoznamCB = new Vector();
        zoznamCB.add("<Pohorie>");
        for (String pohorie : zoznam) {
            zoznamCB.add(pohorie);
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(zoznamCB);
        pohorieComboBox.setModel(model);
        //naplni rocneObdobieComboBox

        zoznam = tury.dajRocneObdobie();
        Vector zoznamROCB = new Vector();
        zoznamROCB.add("<RocneObdobie>");
        for (String ro : zoznam) {
            zoznamROCB.add(ro);
        }
        DefaultComboBoxModel modelRO = new DefaultComboBoxModel(zoznamROCB);
        rocneObdobieComboBox.setModel(modelRO);

        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pohorieLabel = new javax.swing.JLabel();
        pohorieComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        rocneObdobieComboBox = new javax.swing.JComboBox();
        obtiaznostLabel = new javax.swing.JLabel();
        obtiaznostRadioButton1 = new javax.swing.JRadioButton();
        obtiaznostRadioButton2 = new javax.swing.JRadioButton();
        obtiaznostRadioButton3 = new javax.swing.JRadioButton();
        obtiaznostRadioButton4 = new javax.swing.JRadioButton();
        obtiaznostRadioButton5 = new javax.swing.JRadioButton();
        casovaNarLabel = new javax.swing.JLabel();
        casovaNarTextField = new javax.swing.JTextField();
        mimoChodnikLabel = new javax.swing.JLabel();
        mimoChodnikCheckBox = new javax.swing.JCheckBox();
        hodLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pohorieLabel.setText("Pohorie");

        pohorieComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pohorie>" }));
        pohorieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pohorieComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Ročné obdobie");

        rocneObdobieComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rocneObdobieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rocneObdobieComboBoxActionPerformed(evt);
            }
        });

        obtiaznostLabel.setText("Max. obtiažnosť");

        obtiaznostRadioButton1.setText("1");

        obtiaznostRadioButton2.setText("2");

        obtiaznostRadioButton3.setText("3");

        obtiaznostRadioButton4.setText("4");

        obtiaznostRadioButton5.setText("5");

        casovaNarLabel.setText("Max. trvanie túry");

        casovaNarTextField.setText("8");

        mimoChodnikLabel.setText("Off track");

        mimoChodnikCheckBox.setText("áno");

        hodLabel.setText("hod.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pohorieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtiaznostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casovaNarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mimoChodnikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mimoChodnikCheckBox)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pohorieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rocneObdobieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(casovaNarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(obtiaznostRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(obtiaznostRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(obtiaznostRadioButton3)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(obtiaznostRadioButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(obtiaznostRadioButton5)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pohorieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pohorieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rocneObdobieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obtiaznostRadioButton1)
                    .addComponent(obtiaznostRadioButton2)
                    .addComponent(obtiaznostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtiaznostRadioButton3)
                    .addComponent(obtiaznostRadioButton4)
                    .addComponent(obtiaznostRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casovaNarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casovaNarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mimoChodnikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mimoChodnikCheckBox)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pohorieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pohorieComboBoxActionPerformed
        pohorieComboBox.repaint();
    }//GEN-LAST:event_pohorieComboBoxActionPerformed

    private void rocneObdobieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rocneObdobieComboBoxActionPerformed
        rocneObdobieComboBox.repaint();
    }//GEN-LAST:event_rocneObdobieComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterTurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterTurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterTurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterTurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterTurForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casovaNarLabel;
    private javax.swing.JTextField casovaNarTextField;
    private javax.swing.JLabel hodLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox mimoChodnikCheckBox;
    private javax.swing.JLabel mimoChodnikLabel;
    private javax.swing.JLabel obtiaznostLabel;
    private javax.swing.JRadioButton obtiaznostRadioButton1;
    private javax.swing.JRadioButton obtiaznostRadioButton2;
    private javax.swing.JRadioButton obtiaznostRadioButton3;
    private javax.swing.JRadioButton obtiaznostRadioButton4;
    private javax.swing.JRadioButton obtiaznostRadioButton5;
    private javax.swing.JComboBox pohorieComboBox;
    private javax.swing.JLabel pohorieLabel;
    private javax.swing.JComboBox rocneObdobieComboBox;
    // End of variables declaration//GEN-END:variables
}
