package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

public class HostMenu extends javax.swing.JFrame implements MouseListener {

    private JLabel preListener = null;
    private final long hostConst = -1;

    public HostMenu() {
        initComponents();
        this.setTitle("HikeApp");

        BufferedImage searchObrazok = null;
        BufferedImage inspirationObrazok = null;

        try {
            searchObrazok = ImageIO.read(new File("C:\\naMenu\\search1.png"));
            inspirationObrazok = ImageIO.read(new File("C:\\naMenu\\inspiration.png"));

        } catch (IOException ex) {
            System.err.println("Neni obrazok!");
        }
        Image scaledSearch = searchObrazok.getScaledInstance(45,
                40, Image.SCALE_SMOOTH);
        Image scaledInspiration = inspirationObrazok.getScaledInstance(45,
                40, Image.SCALE_SMOOTH);

        hladajLabel.setIcon(new ImageIcon(scaledSearch));
        inspirujLabel.setIcon(new ImageIcon(scaledInspiration));

        hladajLabel.setHorizontalAlignment(JLabel.CENTER);
        hladajLabel.setVerticalAlignment(JLabel.CENTER);

        inspirujLabel.setHorizontalAlignment(JLabel.CENTER);
        inspirujLabel.setVerticalAlignment(JLabel.CENTER);

        hladajLabel.addMouseListener(this);
        inspirujLabel.addMouseListener(this);

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((dim.width - this.getSize().width) / 2, (dim.height - this.getSize().height) / 2);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                HostMenu.this.dispose();
                new LogInForm().setVisible(true);
            }

        });
        //this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hladajLabel = new javax.swing.JLabel();
        inspirujLabel = new javax.swing.JLabel();
        obrazokLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hladajLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(hladajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 85, 70));

        inspirujLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(inspirujLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 85, 70));

        obrazokLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Patrik\\Desktop\\touristic1.png")); // NOI18N
        getContentPane().add(obrazokLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hladajLabel;
    private javax.swing.JLabel inspirujLabel;
    private javax.swing.JLabel obrazokLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if (preListener.equals(hladajLabel)) {
            new FilterTurForm(hostConst).setVisible(true);
            this.dispose();
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        preListener = (JLabel) e.getSource();
        preListener.setBorder(new SoftBevelBorder(BevelBorder.LOWERED));
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        preListener = (JLabel) e.getSource();
        preListener.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        preListener = (JLabel) e.getSource();
        preListener.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    @Override
    public void mouseExited(MouseEvent e) {
        preListener = (JLabel) e.getSource();
        preListener.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
}
