package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import sk.ics.upjs.hikeapp.Uzivatel;
import sk.ics.upjs.hikeapp.UzivatelMysqlDaO;

public class RegisterForm extends javax.swing.JFrame {

    private UzivatelMysqlDaO uzivatelia = new UzivatelMysqlDaO();

    public RegisterForm() {
        initComponents();
        this.setTitle("Ragistrácia užívateľa");
        this.pack();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int height = dim.height;
        int width = dim.width;
        this.setLocation((-this.getSize().width + width) / 2, (-this.getSize().height + height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menoLabel = new javax.swing.JLabel();
        hesloLabel = new javax.swing.JLabel();
        menoTextField = new javax.swing.JTextField();
        hesloField = new javax.swing.JPasswordField();
        registrujButton = new javax.swing.JButton();
        heslo2Field = new javax.swing.JPasswordField();
        heslo2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        menoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menoLabel.setText("Meno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 19, 0, 0);
        getContentPane().add(menoLabel, gridBagConstraints);

        hesloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hesloLabel.setText("Heslo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 0);
        getContentPane().add(hesloLabel, gridBagConstraints);

        menoTextField.setText("Meno");
        menoTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 16, 0, 0);
        getContentPane().add(menoTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 70);
        getContentPane().add(hesloField, gridBagConstraints);

        registrujButton.setText("Registruj");
        registrujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrujButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 11, 70);
        getContentPane().add(registrujButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 70);
        getContentPane().add(heslo2Field, gridBagConstraints);

        heslo2Label.setText("Zopakuj heslo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        getContentPane().add(heslo2Label, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrujButtonActionPerformed
        Uzivatel u = new Uzivatel();
        String meno = menoTextField.getText();
        String heslo = hesloField.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vypíš meno!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!uzivatelia.overMeno(meno.trim())) {
            JOptionPane.showMessageDialog(this, "Meno už existuje!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            u.setMeno(meno.trim());
        }
        if (heslo.trim().length() < 6) {
            JOptionPane.showMessageDialog(this, "Heslo musí mať aspoň 6 znakov!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (heslo.trim().length() > 20) {
            JOptionPane.showMessageDialog(this, "Príliš dlhé heslo!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            u.setHeslo(heslo.trim());
        }
        uzivatelia.vlozUzivatela(u);
        this.dispose();
        new FilterTurForm().setVisible(true);
    }//GEN-LAST:event_registrujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField heslo2Field;
    private javax.swing.JLabel heslo2Label;
    private javax.swing.JPasswordField hesloField;
    private javax.swing.JLabel hesloLabel;
    private javax.swing.JLabel menoLabel;
    private javax.swing.JTextField menoTextField;
    private javax.swing.JButton registrujButton;
    // End of variables declaration//GEN-END:variables
}
